DELIMITER //

DROP PROCEDURE IF EXISTS getCities //
CREATE PROCEDURE getCities (
	IN inCityId VARCHAR(100),
    OUT statusCode INT
)
BEGIN
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		GET STACKED DIAGNOSTICS CONDITION 1 @p1 = MYSQL_ERRNO;
		SET statusCode = @p1;
		ROLLBACK;
	END;

    START TRANSACTION;

	IF inCityId NOT IN (SELECT cityId FROM cities) THEN
		SIGNAL SQLSTATE '45000'
			SET MYSQL_ERRNO = 460; -- invalid city id 
	END IF;
    
    SET statusCode = 200;

	SELECT cityId
    FROM cities
    WHERE cityId = inCityId;
END//

DELIMITER ;