/*
	Get all information about a court given the court id
*/
DELIMITER //

DROP PROCEDURE IF EXISTS getCourtInfo//
CREATE PROCEDURE getCourtInfo(
	in inCourtId INT
)
BEGIN
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		GET STACKED DIAGNOSTICS CONDITION 1 @p1 = MYSQL_ERRNO, @p2 = MESSAGE_TEXT;
		SELECT @p1 AS `STATUS_CODE`, @p2 AS `STATUS_MESSAGE`;
		ROLLBACK;
	END;

	START TRANSITION;

	IF inCourtId NOT IN (SELECT courtId FROM courts) THEN
		SIGNAL SQLSTATE '45000'
			SET MYSQL_ERRNO = 469;
	END IF;

	SELECT *
	FROM courts
	WHERE courtId = inCourtId;
END//

DELIMITER ;